package cfl

var MockScheduleResponse = CFLScheduleResponse{
	{
		ID:        1317793,
		Status:    "complete",
		Name:      "Preseason Week 1",
		Type:      "PRE",
		Number:    1,
		StartDate: "2025-05-19T00:00:00+00:00",
		EndDate:   "2025-05-20T23:59:00+00:00",
		Tournaments: []CFLGame{
			{
				ID:     11824097,
				Date:   "2025-05-19T20:00:00+00:00",
				Status: "live",
				HomeSquad: CFLTeam{
					ID:        93775,
					Name:      "Winnipeg Blue Bombers",
					ShortName: "WPG",
					Score:     14,
				},
				AwaySquad: CFLTeam{
					ID:        112939,
					Name:      "Saskatchewan Roughriders",
					ShortName: "SSK",
					Score:     10,
				},
				ActivePeriod: "HT",
				Timeouts: CFLTimeouts{
					Away: 2,
					Home: 1,
				},
				Possession: "WPG",
				CFLID:      6487,
				Clock:      "HALFTIME",
				Winner:     nil,
				IsHidden:   false,
			},
		},
	},
}

var MockLiveGameResponse = CFLLiveGameResponse{
	Data: CFLLiveGameData{
		BetGeniusFixtureID: "11824097",
		ScoreboardInfo: CFLScoreboardInfo{
			MatchStatus:          "live",
			CurrentPhase:         "Q2",
			AwayScore:            10,
			HomeScore:            14,
			AwayTimeoutsLeft:     2,
			HomeTimeoutsLeft:     1,
			TotalTimeouts:        2,
			TimeRemainingInPhase: "12:34",
			Possession:           "WPG",
			Down:                 2,
			YardsToGo:            8,
			TotalPhases:          2,
			PhaseQualifier:       "Regular",
			ClockUnreliable:      false,
		},
		LiveStream: CFLLiveStream{
			CurrentPlay: CFLCurrentPlay{
				DownNumber:      2,
				LineOfScrimmage: 45,
				FirstDownLine:   53,
				PlayType:        "pass",
				YardsToGo:       8,
				Possession:      "WPG",
				Clock:           "12:34",
				Phase:           "Q2",
				PlayFormation:   "shotgun",
				Quarterback:     12345,
				YardLine: CFLYardLine{
					TeamNumber: 1,
					YardLine:   45,
				},
			},
			CurrentDrive: CFLCurrentDrive{
				YardsGained:           5,
				TimeOfPossession:      "3:45",
				HowObtained:           "KICKOFF",
				HowLost:               "",
				Plays:                 6,
				StartingFieldPosition: 20,
				CurrentFieldPosition:  45,
				DriveStart: CFLYardLine{
					TeamNumber: 2,
					YardLine:   20,
				},
				DriveEnd: CFLYardLine{
					TeamNumber: 1,
					YardLine:   45,
				},
			},
			Actions: []CFLAction{
				{
					ActionType:  "pass",
					Description: "Zach Collaros pass complete to Nic Demski for 12 yards",
					YardsGained: 12,
					Clock:       "13:45",
					Down:        1,
					Distance:    10,
					Possession:  "WPG",
					YardLine:    33,
					PlayerId:    12345,
					ReceiverId:  67890,
				},
				{
					ActionType:  "rush",
					Description: "Brady Oliveira rush for 3 yards",
					YardsGained: 3,
					Clock:       "13:12",
					Down:        2,
					Distance:    7,
					Possession:  "WPG",
					YardLine:    36,
					PlayerId:    11111,
				},
				{
					ActionType:  "incomplete_pass",
					Description: "Zach Collaros pass incomplete to Kenny Lawler",
					YardsGained: 0,
					Clock:       "12:45",
					Down:        3,
					Distance:    4,
					Possession:  "WPG",
					YardLine:    36,
					PlayerId:    12345,
					ReceiverId:  22222,
				},
				{
					ActionType:  "field_goal",
					Description: "Marc Liegghio 32-yard field goal attempt GOOD",
					YardsGained: 0,
					Clock:       "12:20",
					Down:        4,
					Distance:    4,
					Possession:  "WPG",
					YardLine:    36,
					PlayerId:    33333,
				},
			},
		},
		MatchInfo: CFLMatchInfo{
			RoundID:            "1279423",
			RoundName:          "Week 14",
			ScheduledStartTime: "2025-09-05T23:30:00+00:00",
			VenueName:          "IG Field",
			SeasonID:           "153593",
			SeasonName:         "2025 CFL",
			HomeTeam: CFLDetailedTeam{
				FullName:     "Winnipeg Blue Bombers",
				CompetitorID: "93775",
				Details: CFLTeamDetails{
					Key:          "93775",
					FirstName:    "Winnipeg",
					ShortName:    "Blue Bombers",
					SecondName:   "Blue Bombers",
					Abbreviation: "WPG",
					OfficialName: "Winnipeg Blue Bombers",
				},
			},
			AwayTeam: CFLDetailedTeam{
				FullName:     "Saskatchewan Roughriders",
				CompetitorID: "112939",
				Details: CFLTeamDetails{
					Key:          "112939",
					FirstName:    "Saskatchewan",
					ShortName:    "Roughriders",
					SecondName:   "Roughriders",
					Abbreviation: "SSK",
					OfficialName: "Saskatchewan Roughriders",
				},
			},
			PlayedPhases: []string{"Q1", "HL"},
		},
	},
	Sport:         "AmericanFootball",
	SportID:       17,
	CompetitionID: 1035,
}
