before:
  hooks:
    - go mod tidy
    - go generate ./...
    - cd web/frontend && npm ci && npm run build

builds:
  - id: goalfeed
    main: ./main.go
    binary: goalfeed
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=netgo
      - -ldflags=-extldflags=-static

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
      - 386
    goarm:
      - 6  # for armhf
      - 7  # for armv7

archives:
  - id: goalfeed
    format: tar.gz
    files:
      - README.md
      - web/frontend/build/**

release:
  github:
    owner: goalfeed
    name: goalfeed

