create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci';
alter table `users` add unique `users_email_unique`(`email`);
create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci';
alter table `password_resets` add index `password_resets_email_index`(`email`);
alter table `password_resets` add index `password_resets_token_index`(`token`);
create table `games` (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `start_time` int unsigned not null, `game_code` varchar(255) not null) default character set utf8 collate 'utf8_unicode_ci';
create table `teams` (`id` int unsigned not null auto_increment primary key, `team_code` text not null, `team_name` text not null) default character set utf8 collate 'utf8_unicode_ci';
create table `game_team` (`id` int unsigned not null auto_increment primary key, `game_id` int unsigned not null, `team_id` int unsigned not null) default character set utf8 collate 'utf8_unicode_ci';
create table `jobs` (`id` bigint unsigned not null auto_increment primary key, `queue` varchar(255) not null, `payload` longtext not null, `attempts` tinyint unsigned not null, `reserved_at` int unsigned null, `available_at` int unsigned not null, `created_at` int unsigned not null) default character set utf8 collate 'utf8_unicode_ci';
alter table `jobs` add index `jobs_queue_reserved_at_index`(`queue`, `reserved_at`);
alter table `games` add `listener_status` varchar(255) not null default 'idle';
drop table if exists `leagues`;
create table `leagues` (`id` int unsigned not null auto_increment primary key, `short_name` text not null, `long_name` text not null) default character set utf8 collate 'utf8_unicode_ci';
alter table `games` add `league_id` int not null;
alter table `teams` add `league_id` int not null;
alter table `users` add `is_admin` tinyint(1) not null default '0';
truncate `games`;
alter table `games` drop `game_code`;
alter table `games` add `game_code` int not null;
alter table `games` add unique `games_game_code_unique`(`game_code`);
alter table `users` add `stripe_id` varchar(255) null, add `card_brand` varchar(255) null, add `card_last_four` varchar(255) null, add `trial_ends_at` timestamp null;
create table `subscriptions` (`id` int unsigned not null auto_increment primary key, `user_id` int not null, `name` varchar(255) not null, `stripe_id` varchar(255) not null, `stripe_plan` varchar(255) not null, `quantity` int not null, `trial_ends_at` timestamp null, `ends_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci';
alter table `users` add `user_type` enum('normal', 'admin', 'free') not null default 'normal';
alter table `users` drop `is_admin`;
create table `listeners` (`id` int unsigned not null auto_increment primary key, `start_time` int unsigned not null default '0', `stop_time` int unsigned not null default '0', `status` enum('running', 'halt', 'finished') not null) default character set utf8 collate 'utf8_unicode_ci';
alter table `games` add `home_points` int not null default '0', add `away_points` int not null default '0', add `cooldown` int not null default '120';
create table `goals` (`id` int unsigned not null auto_increment primary key, `team_id` int unsigned not null, `game_id` int unsigned not null, `timestamp` int unsigned not null) default character set utf8 collate 'utf8_unicode_ci';
alter table `goals` add index `goals_timestamp_index`(`timestamp`);
alter table `users` add `last_connected` int unsigned null default '0';
alter table `games` add `diff_timestamp` text null;
alter table `teams` add `ext_id` varchar(255) null;
