// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/yourusername/goalfeed/issues"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clear": {
            "post": {
                "description": "Clears all games from the memory store. Useful for testing and resetting state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Clear all games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/debug/nfl/add": {
            "post": {
                "description": "Force-adds an NFL game by ESPN event ID. Debug endpoint for testing.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "debug"
                ],
                "summary": "Add NFL game (Debug)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ESPN event ID",
                        "name": "event",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Game"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "Returns a filtered list of game events (goals, scores, etc.) with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by league ID (1=NHL, 2=MLB, 5=CFL, 6=NFL)",
                        "name": "leagueId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by team code",
                        "name": "team",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter events since timestamp (RFC3339)",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of events to return (default: 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/games": {
            "get": {
                "description": "Returns a list of all currently active games across all monitored leagues",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get all active games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Game"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/homeassistant/config": {
            "get": {
                "description": "Returns the current Home Assistant configuration (URL and token status)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homeassistant"
                ],
                "summary": "Get Home Assistant configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Updates the Home Assistant URL and access token for integration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homeassistant"
                ],
                "summary": "Update Home Assistant configuration",
                "parameters": [
                    {
                        "description": "Home Assistant configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webApi.haConfigBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/homeassistant/status": {
            "get": {
                "description": "Checks the connection status to Home Assistant and returns configuration details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homeassistant"
                ],
                "summary": "Get Home Assistant connection status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/leagues": {
            "get": {
                "description": "Returns the list of all supported leagues and their monitored teams",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leagues"
                ],
                "summary": "Get league configurations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Updates the list of monitored teams for a specific league",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leagues"
                ],
                "summary": "Update league configuration",
                "parameters": [
                    {
                        "description": "League configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "leagueId": {
                                    "type": "integer"
                                },
                                "teams": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/logs": {
            "get": {
                "description": "Returns application logs with optional filters for debugging and monitoring",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Get application logs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by league ID",
                        "name": "leagueId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by team code",
                        "name": "team",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter logs since timestamp (RFC3339)",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of log entries to return (0 = all)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.AppLogEntry"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Triggers a refresh of all active games from external APIs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Refresh active games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "description": "Returns a list of all teams for a specific league with logos and metadata",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "Get all teams for a league",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "League ID (1=NHL, 2=MLB, 5=CFL, 6=NFL)",
                        "name": "leagueId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        },
        "/upcoming": {
            "get": {
                "description": "Returns a list of upcoming games for monitored teams within the next 7 days",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get upcoming games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webApi.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Game"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/webApi.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AppLogEntry": {
            "type": "object",
            "properties": {
                "after": {
                    "description": "new value"
                },
                "before": {
                    "description": "previous value"
                },
                "correlationId": {
                    "description": "link to event.id",
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "event": {
                    "description": "for event type",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Event"
                        }
                    ]
                },
                "gameCode": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "leagueId": {
                    "type": "integer"
                },
                "leagueName": {
                    "type": "string"
                },
                "level": {
                    "$ref": "#/definitions/models.AppLogLevel"
                },
                "message": {
                    "type": "string"
                },
                "metric": {
                    "description": "for state_change",
                    "type": "string"
                },
                "opponent": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "success": {
                    "description": "delivery result, if applicable",
                    "type": "boolean"
                },
                "target": {
                    "description": "e.g., HA entity_id or event name",
                    "type": "string"
                },
                "teamCode": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.AppLogType"
                }
            }
        },
        "models.AppLogLevel": {
            "type": "string",
            "enum": [
                "debug",
                "info",
                "warn",
                "error"
            ],
            "x-enum-varnames": [
                "AppLogLevelDebug",
                "AppLogLevelInfo",
                "AppLogLevelWarn",
                "AppLogLevelError"
            ]
        },
        "models.AppLogType": {
            "type": "string",
            "enum": [
                "event",
                "state_change",
                "log"
            ],
            "x-enum-varnames": [
                "AppLogTypeEvent",
                "AppLogTypeStateChange",
                "AppLogTypeLogLine"
            ]
        },
        "models.BaseRunners": {
            "type": "object",
            "properties": {
                "first": {
                    "$ref": "#/definitions/models.Player"
                },
                "second": {
                    "$ref": "#/definitions/models.Player"
                },
                "third": {
                    "$ref": "#/definitions/models.Player"
                }
            }
        },
        "models.Broadcaster": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                }
            }
        },
        "models.Event": {
            "type": "object",
            "properties": {
                "broadcasters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Broadcaster"
                    }
                },
                "clock": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "details": {
                    "description": "Event details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.EventDetails"
                        }
                    ]
                },
                "gameCode": {
                    "type": "string"
                },
                "gameId": {
                    "type": "string"
                },
                "id": {
                    "description": "Basic event info",
                    "type": "string"
                },
                "leagueId": {
                    "description": "Game context",
                    "type": "integer"
                },
                "leagueName": {
                    "type": "string"
                },
                "opponentCode": {
                    "description": "Opponent info",
                    "type": "string"
                },
                "opponentHash": {
                    "type": "string"
                },
                "opponentName": {
                    "type": "string"
                },
                "period": {
                    "type": "integer"
                },
                "playerName": {
                    "type": "string"
                },
                "playerNumber": {
                    "type": "integer"
                },
                "score": {
                    "$ref": "#/definitions/models.ScoreUpdate"
                },
                "teamCode": {
                    "description": "Team and player info",
                    "type": "string"
                },
                "teamHash": {
                    "type": "string"
                },
                "teamName": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.EventType"
                },
                "venue": {
                    "description": "Venue and broadcast info",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Venue"
                        }
                    ]
                }
            }
        },
        "models.EventDetails": {
            "type": "object",
            "properties": {
                "assist1": {
                    "$ref": "#/definitions/models.Player"
                },
                "assist2": {
                    "$ref": "#/definitions/models.Player"
                },
                "ballCount": {
                    "type": "integer"
                },
                "baseRunners": {
                    "description": "Enhanced baseball details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.BaseRunners"
                        }
                    ]
                },
                "bases": {
                    "description": "\"empty\", \"1st\", \"2nd\", \"3rd\", \"loaded\"",
                    "type": "string"
                },
                "batter": {
                    "$ref": "#/definitions/models.Player"
                },
                "distance": {
                    "type": "integer"
                },
                "down": {
                    "type": "integer"
                },
                "goalType": {
                    "description": "Goal details",
                    "type": "string"
                },
                "inning": {
                    "description": "Baseball details",
                    "type": "integer"
                },
                "outs": {
                    "type": "integer"
                },
                "penaltyMinutes": {
                    "type": "integer"
                },
                "penaltyType": {
                    "description": "Penalty details",
                    "type": "string"
                },
                "pitchCount": {
                    "type": "integer"
                },
                "pitcher": {
                    "$ref": "#/definitions/models.Player"
                },
                "possession": {
                    "description": "Team code with possession",
                    "type": "string"
                },
                "strikeCount": {
                    "type": "integer"
                },
                "yardLine": {
                    "description": "Play details",
                    "type": "integer"
                },
                "yardsGained": {
                    "type": "integer"
                }
            }
        },
        "models.EventType": {
            "type": "string",
            "enum": [
                "goal",
                "assist",
                "penalty",
                "power_play",
                "shot",
                "hit",
                "faceoff",
                "save",
                "turnover",
                "fumble",
                "interception",
                "touchdown",
                "field_goal",
                "safety",
                "home_run",
                "strikeout",
                "walk",
                "error",
                "period_start",
                "period_end",
                "game_start",
                "game_end"
            ],
            "x-enum-varnames": [
                "EventTypeGoal",
                "EventTypeAssist",
                "EventTypePenalty",
                "EventTypePowerPlay",
                "EventTypeShot",
                "EventTypeHit",
                "EventTypeFaceoff",
                "EventTypeSave",
                "EventTypeTurnover",
                "EventTypeFumble",
                "EventTypeInterception",
                "EventTypeTouchdown",
                "EventTypeFieldGoal",
                "EventTypeSafety",
                "EventTypeHomeRun",
                "EventTypeStrikeout",
                "EventTypeWalk",
                "EventTypeError",
                "EventTypePeriodStart",
                "EventTypePeriodEnd",
                "EventTypeGameStart",
                "EventTypeGameEnd"
            ]
        },
        "models.Game": {
            "type": "object",
            "properties": {
                "currentState": {
                    "$ref": "#/definitions/models.GameState"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GameEvent"
                    }
                },
                "extTimestamp": {
                    "type": "string"
                },
                "gameCode": {
                    "type": "string"
                },
                "gameDetails": {
                    "description": "Enhanced fields",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.GameDetails"
                        }
                    ]
                },
                "isFetching": {
                    "type": "boolean"
                },
                "leagueId": {
                    "type": "integer"
                },
                "statistics": {
                    "$ref": "#/definitions/models.GameStats"
                }
            }
        },
        "models.GameDetails": {
            "type": "object",
            "properties": {
                "broadcasters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Broadcaster"
                    }
                },
                "gameDate": {
                    "type": "string"
                },
                "gameId": {
                    "type": "string"
                },
                "gameTime": {
                    "type": "string"
                },
                "officials": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Official"
                    }
                },
                "season": {
                    "type": "string"
                },
                "seasonType": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "week": {
                    "type": "integer"
                }
            }
        },
        "models.GameEvent": {
            "type": "object",
            "properties": {
                "clock": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "details": {
                    "$ref": "#/definitions/models.EventDetails"
                },
                "id": {
                    "type": "string"
                },
                "period": {
                    "type": "integer"
                },
                "player": {
                    "$ref": "#/definitions/models.Player"
                },
                "team": {
                    "$ref": "#/definitions/models.Team"
                },
                "time": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.EventType"
                }
            }
        },
        "models.GameState": {
            "type": "object",
            "properties": {
                "away": {
                    "$ref": "#/definitions/models.TeamState"
                },
                "clock": {
                    "type": "string"
                },
                "details": {
                    "description": "Baseball-specific details",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.EventDetails"
                        }
                    ]
                },
                "extTimestamp": {
                    "type": "string"
                },
                "fetchedAt": {
                    "type": "string"
                },
                "home": {
                    "$ref": "#/definitions/models.TeamState"
                },
                "period": {
                    "description": "Enhanced game state",
                    "type": "integer"
                },
                "periodType": {
                    "description": "\"REGULAR\", \"OVERTIME\", \"SHOOTOUT\", etc.",
                    "type": "string"
                },
                "statistics": {
                    "$ref": "#/definitions/models.TeamStats"
                },
                "status": {
                    "type": "integer"
                },
                "timeRemaining": {
                    "type": "string"
                },
                "venue": {
                    "$ref": "#/definitions/models.Venue"
                },
                "weather": {
                    "$ref": "#/definitions/models.Weather"
                }
            }
        },
        "models.GameStats": {
            "type": "object",
            "properties": {
                "penalties": {
                    "type": "integer"
                },
                "penaltyYards": {
                    "type": "integer"
                },
                "timeOfPossession": {
                    "type": "string"
                },
                "totalPlays": {
                    "type": "integer"
                },
                "totalYards": {
                    "type": "integer"
                },
                "turnovers": {
                    "type": "integer"
                }
            }
        },
        "models.Official": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "models.Player": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "position": {
                    "type": "string"
                },
                "team": {
                    "$ref": "#/definitions/models.Team"
                }
            }
        },
        "models.ScoreUpdate": {
            "type": "object",
            "properties": {
                "awayScore": {
                    "type": "integer"
                },
                "awayTeam": {
                    "type": "string"
                },
                "homeScore": {
                    "type": "integer"
                },
                "homeTeam": {
                    "type": "string"
                }
            }
        },
        "models.Team": {
            "type": "object",
            "properties": {
                "extId": {
                    "type": "string"
                },
                "leagueId": {
                    "type": "integer"
                },
                "logoUrl": {
                    "type": "string"
                },
                "teamCode": {
                    "type": "string"
                },
                "teamId": {
                    "type": "integer"
                },
                "teamName": {
                    "type": "string"
                }
            }
        },
        "models.TeamState": {
            "type": "object",
            "properties": {
                "periodScores": {
                    "description": "Enhanced team state",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "score": {
                    "type": "integer"
                },
                "statistics": {
                    "$ref": "#/definitions/models.TeamStats"
                },
                "team": {
                    "$ref": "#/definitions/models.Team"
                }
            }
        },
        "models.TeamStats": {
            "type": "object",
            "properties": {
                "baseballHits": {
                    "description": "MLB",
                    "type": "integer"
                },
                "errors": {
                    "type": "integer"
                },
                "faceoffs": {
                    "type": "integer"
                },
                "firstDowns": {
                    "description": "League-specific stats\nNFL/CFL",
                    "type": "integer"
                },
                "hits": {
                    "type": "integer"
                },
                "passingYards": {
                    "type": "integer"
                },
                "penalties": {
                    "type": "integer"
                },
                "penaltyYards": {
                    "type": "integer"
                },
                "plays": {
                    "description": "General stats",
                    "type": "integer"
                },
                "powerPlays": {
                    "type": "integer"
                },
                "rushingYards": {
                    "type": "integer"
                },
                "shots": {
                    "description": "NHL",
                    "type": "integer"
                },
                "strikeouts": {
                    "type": "integer"
                },
                "timeOfPossession": {
                    "type": "string"
                },
                "turnovers": {
                    "type": "integer"
                },
                "walks": {
                    "type": "integer"
                },
                "yards": {
                    "type": "integer"
                }
            }
        },
        "models.Venue": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "indoor": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "surface": {
                    "type": "string"
                }
            }
        },
        "models.Weather": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string"
                },
                "humidity": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "integer"
                },
                "windDirection": {
                    "type": "string"
                },
                "windSpeed": {
                    "type": "integer"
                }
            }
        },
        "webApi.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "webApi.haConfigBody": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "your-long-lived-access-token"
                },
                "clearToken": {
                    "type": "boolean",
                    "example": false
                },
                "url": {
                    "type": "string",
                    "example": "http://homeassistant.local:8123"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Goalfeed API",
	Description:      "Real-time sports monitoring API for NHL, MLB, NFL, CFL, and IIHF games.\nProvides game state, events, and team management for Home Assistant integration and web consumers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
